### ISSUE TITLE
./runTests -test test1_1 fails on ppc64 platform

### ISSUE THREAD

**Issue by mcfadden8** [dyninst/dyninst#8]
[ppc64.verbose.debugstartup.txt](https://github.com/dyninst/dyninst/files/249567/ppc64.verbose.debugstartup.txt)
[ppc64.verbose.txt](https://github.com/dyninst/dyninst/files/249566/ppc64.verbose.txt)

test1_1 causes a core dump (I can provide that if needed).  The two log
files attached are from two separate runs.  One with and one without
DYNINST_DEBUG_STARTUP set.

**Comment by mcfadden8** [comment]
From Bill Williams:
The debugging asserts in emitElf64.C at lines 2123 and 2127 should go away; they're *obviously* x86-only sanity checks.

**Comment by mcfadden8** [comment]
I removed those lines, recompiled and seem to have made it to the next
layer of the onion.  The test still fails.  Logs attached.
[ppc64.verbose.debugstartup(1).txt](https://github.com/dyninst/dyninst/files/249572/ppc64.verbose.debugstartup.1.txt)
[ppc64.verbose(1).txt](https://github.com/dyninst/dyninst/files/249573/ppc64.verbose.1.txt)

**Comment by wrwilliams** [comment]
This next layer is fixed in a patch @morehouse will be sending up.

**Comment by mcfadden8** [comment]
Okay, will the patch be in dyninst or testsuite?

Also, will you be providing the dyninst patch to emitElf64.C from above?

**Comment by wrwilliams** [comment]
Dyninst; commit ID is b3abbed and can be cherry-picked from the sfm branch.
I can commit the assertion cleanup once I get into the office today.

**Comment by morehouse** [comment]
The patch has been applied to master and v9.2.x.  Could you try the test on ppc64 again?

**Comment by mcfadden8** [comment]
The behavior has changed but unfortunately the test is still not working on ppc64.  Instead the test seems to just hang.  

Please see the following attached logs:
[ppc64.verbose.debugstartup(2).txt](https://github.com/dyninst/dyninst/files/251210/ppc64.verbose.debugstartup.2.txt)
[ppc64.verbose(2).txt](https://github.com/dyninst/dyninst/files/251209/ppc64.verbose.2.txt)

**Comment by wrwilliams** [comment]
...14 call edges in _start? That's unusual, and either a sign that the toolchains have passed us by or that something is *really* confused.

There's a CFG generating example in the parseAPI docs; I'd be interested to see what we turn up for _start as compared with an objdump log.

**Comment by mcfadden8** [comment]
Is there something specific you would like for me to provide or is this question directed at someone else?

**Comment by wrwilliams** [comment]
Sorry, yes, I can be more specific.

objdump -d dyninst_cxx_group_test.dyn_g++_64_none_none and cut out _start; that's what we're trying to parse to find main's entry point.
parseAPI/doc has a file, example.cc, that can be built as a standard mutator (-I/path/to/dyninst/include -L/path/to/dyninst/lib -lparseAPI). It takes a binary and outputs its CFG in dot form. There should be a subgraph for _start.

If you snip both of those into gists, I can at least make some headway without needing to get into a machine.

**Comment by mcfadden8** [comment]
I've not used gists before so I don't know how to link to them from here.

Here is objdump output:
  1 000000001000463c <._start>:
  2     1000463c:  7c 29 0b 78    mr      r9,r1
  3     10004640:  78 21 06 e4    rldicr  r1,r1,0,59
  4     10004644:  38 00 00 00    li      r0,0
  5     10004648:  f8 21 ff 81    stdu    r1,-128(r1)
  6     1000464c:  7c 08 03 a6    mtlr    r0
  7     10004650:  f8 01 00 00    std     r0,0(r1)
  8     10004654:  e9 02 80 20    ld      r8,-32736(r2)
  9     10004658:  4b ff fe 18    b       10004470 <00000011.plt_call.__libc_start_main@@GLIBC_2.3+0>
 10     1000465c:  e8 41 00 28    ld      r2,40(r1)
 11     10004660:  00 00 00 00    .long 0x0
 12     10004664:  00 0c 20 40    .long 0xc2040
 13     10004668:  00 00 00 00    .long 0x0
 14     1000466c:  00 00 00 24    .long 0x24
 15     10004670:  00 06 5f 73    .long 0x65f73
 16     10004674:  74 61 72 74    andis.  r1,r3,29300
 17     10004678:  60 00 00 00    nop
 18     1000467c:  60 00 00 00    nop

**Comment by wrwilliams** [comment]
That's about as simple as it gets...that's not even an indirect tail call, that's a regular and boring tail call. The parser should say that _start is a single block ending in a tail call, which we should follow to libc_start_main and thence to the code that reads the pointer to main. And none of that is code that should have changed, except inasmuch as x86 parsing changes have had unsavory implications on power.

I'll look some more at this tomorrow.

**Comment by mcfadden8** [comment]
[My first gist attempt for requested objdump and CFG](https://gist.github.com/mcfadden8/46d152dcf9a331d052fbd5732d792b10)

**Comment by wrwilliams** [comment]
Came through nice and clear. Thanks.

**Comment by wrwilliams** [comment]
Is the system that's producing this bug running the v2 ABI?

**Comment by mcfadden8** [comment]
No it it not.  It is running Big Endian and is still running v1.

**Comment by wrwilliams** [comment]
Then this is definitely still a fix for 9.2, not a defer until we properly handle ABIv2.

DYNINST_DEBUG_STARTUP has told me all it can (and I misread the initial startup logs; we're allowed to be confused by libc's _start function, but not the executable's); DYNINST_DEBUG_INST looks like the next place to look for useful data.

If this is on vulcan (or any other CZ machine sharing that filesystem?) I can get my account working again and pick up your repository as a starting point.

**Comment by mcfadden8** [comment]
Okay, these particular tests are being run on the restricted network.  Vulcan should work and I believe you should be able to git clone directly from github (I am able to at any rate)?

**Comment by wrwilliams** [comment]
Also true. I presume your fork is up-to-date?

**Comment by mcfadden8** [comment]
Pretty close.  I haven't pull over the three commits you just did yet.

**Comment by mcfadden8** [comment]
FYI,

When I run this on Vulcan, I get slightly different results:

./runTests -test test1_1
TEST                       COMP   OPT  ABI MODE     THREAD  LINK    PIC     RESULT
test1_1                    g++    none 64  create   NA      dynamic nonPIC  PASSED
test1_1                    g++    none 64  rewriter NA      dynamic nonPIC  CRASHED (Group Teardown)

**Comment by wrwilliams** [comment]
Very interesting; there's some environmental difference on the RZ machine that's screwing up create. Do you know if that's one I can get access to?

**Comment by mcfadden8** [comment]
I believe so yes.  The machine is rzuseq.

**Comment by mcfadden8** [comment]
Something has changed over the last 5 days.   After pulling over all of the latest and greatest, both machines are producing the same results which are both different from what was originally reported.

Here is what I see now on both Vulcan and Useq:
$ ./runTests -test test1_1       
TEST                       COMP   OPT  ABI MODE     THREAD  LINK    PIC     RESULT
test1_1                    g++    none 64  create   NA      dynamic nonPIC  PASSED
test1_1                    g++    none 64  rewriter NA      dynamic nonPIC  CRASHED (Group Teardown)

**Comment by wrwilliams** [comment]
Okay, good. I'm getting the same thing on vulcan, and it looks like all our rewriter tests are producing broken binaries. This is not a surprise, given that I refactored that code pretty heavily. I'm going to get a more useful set of issues from my current test run, split things out, and close this one.

And yes, I can get to rzuseq but there's no point if it and vulcan are in sync with each other.

**Comment by wrwilliams** [comment]
Replaced by #33, #34, #35, #36.
